# Налаштування для Minikube
service:
  type: ClusterIP
  port: 5000

extraEnvVars:
  - name: AWS_ACCESS_KEY_ID
    value: "minio"
  - name: AWS_SECRET_ACCESS_KEY
    value: "minio123"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio.application.svc.cluster.local:9000"
  - name: MLFLOW_BACKEND_STORE_URI
    value: "postgresql://mlflow:mlflowpass@mlflow-postgres-postgresql.application.svc.cluster.local:5432/mlflow"
  - name: MLFLOW_ARTIFACT_ROOT
    value: "s3://mlflow-artifacts"

postgresql:
  enabled: false
